### ISSUE TITLE
Video 2f

### ISSUE THREAD

**Issue by m2web** [miguelgrinberg/oreilly-intro-to-flask-video#3]
Miguel, Moving forward in the video lessons, which are very helpful BTW, I ran into another issue with running the weather.py script in 2f:

```
(venv) mark@mark-netbook:~/python/oreilly-intro-to-flask-video/2f$ python weather.py 
Traceback (most recent call last):
  File "weather.py", line 2, in <module>
    from flask.ext.bootstrap import Bootstrap
  File "/home/mark/python/oreilly-intro-to-flask-video/venv/lib/python3.4/site-packages/flask/exthook.py", line 87, in load_module
    raise ImportError('No module named %s' % fullname)
ImportError: No module named flask.ext.bootstrap
```

Before attempting my own pip install flask-bootstrap I wanted to pass this to you.

**Comment by najeebullahshah** [comment]
Install pip and then use the following command:

C:\Python27\scripts>pip install Flask-Bootstrap
